In [15]:
import pandas as pd
tips = pd.read_csv('../Data/tip.csv')
booking = pd.read_csv('../Data/bookings.csv')

In [16]:
# bill count
a = tips.groupby("day")["total_bill"].size()
print(a)

# avg bill
b = tips.groupby("day")["total_bill"].mean()
print(b)

#tip avg
c = tips.groupby("day")["tip"].mean()
print(c)


# all together
# d = tips.groupby("day").agg({"total_bill": ["size", "mean"], "tip": "mean"})
# print(d)


tips.groupby("day").agg(
    Bill_count = ("total_bill", "size"),
    Bill_avg =("total_bill", "mean"),
    Bill_tip = ("tip", "mean")
)

day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_bill, dtype: int64
day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.682742
Name: total_bill, dtype: float64
day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

      Bill_count   Bill_avg  Bill_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [17]:
tips.groupby("time").agg(
    Bill_count = ("total_bill", "size"),
    Bill_avg =("total_bill", "mean"),
    Avg_party = ("size", "mean")
)

        Bill_count   Bill_avg  Avg_party
time
Dinner         176  20.797159   2.630682
Lunch           68  17.168676   2.411765

In [18]:
# only good days
# the day where the avg tip is under 3

summary = tips.groupby("day").agg(
    Bill_count = ("total_bill", "size"),
    Bill_avg =("total_bill", "mean"),
    Avg_tip = ("tip", "mean")
).round(2)

# the round function rounds the values to 2 decimal places
print(summary)

summary[summary["Avg_tip"] <= 3]

# summary[summary["day"] == "Sun"] gives error cuz the day column is not in the summary dataframe. It is an index. So we need to use .loc to access it.
# the column we use to groupby becomes the index of the resulting dataframe. So we need to use .loc to access it.

      Bill_count  Bill_avg  Avg_tip
day
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Sun           76     21.41     3.26
Thur          62     17.68     2.77

      Bill_count  Bill_avg  Avg_tip
day
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Thur          62     17.68     2.77

In [19]:
# making the index a column again
print(summary.columns.to_list())

print(summary.index.to_list())


# reset_index() makes the index a column again. It also creates a new index for the dataframe. 
# The new index is a range index starting from 0. The old index is added as a new column to the dataframe.
#  The name of the new column is the name of the old index. If the old index has no name, the new column will be named 'index'. 
# If the old index has a name, the new column will be named after the old index's name.
flat = summary.reset_index()
print(flat.columns.to_list())
flat.head()

['Bill_count', 'Bill_avg', 'Avg_tip']
['Fri', 'Sat', 'Sun', 'Thur']
['day', 'Bill_count', 'Bill_avg', 'Avg_tip']

    day  Bill_count  Bill_avg  Avg_tip
0   Fri          19     17.15     2.73
1   Sat          87     20.44     2.99
2   Sun          76     21.41     3.26
3  Thur          62     17.68     2.77

In [20]:
# email me the file.
# wants summary to_csv() and send it to me.

summary.to_csv("summary.csv")
flat= pd.read_csv("summary.csv")
print(flat.head())

    day  Bill_count  Bill_avg  Avg_tip
0   Fri          19     17.15     2.73
1   Sat          87     20.44     2.99
2   Sun          76     21.41     3.26
3  Thur          62     17.68     2.77

In [21]:
# somking-section report.
# per smoker grp, the no of bills, avg bill, avg tip. save the report as a csv file, so that YES/NO lable survives

smoker_summary = tips.groupby("smoker").agg(
    Bill_count = ("total_bill", "size"),
    Bill_avg =("total_bill", "mean"),
    Avg_tip = ("tip", "mean")
).round(2)

# reset indeex
flat = smoker_summary.reset_index()
print(flat.columns.to_list())
flat.head() 

# converting into csv file
smoker_summary.to_csv("smoker_summary.csv")

# printing the csv file
flat= pd.read_csv("smoker_summary.csv")
print(flat.head())

['smoker', 'Bill_count', 'Bill_avg', 'Avg_tip']
  smoker  Bill_count  Bill_avg  Avg_tip
0     No         151     19.19     2.99
1    Yes          93     20.76     3.01

In [22]:
# who left the max tips

# return index label of the row holding max tips
print(tips.groupby("day")["tip"].idxmax())  # it tells the idx of the tip
print(tips.groupby("day")["tip"].max())    # it tells the max values of the tip

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64
day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64

In [23]:
tips.loc[183]
# here loc tells the summary of the idxmax detail

total_bill     23.17
tip              6.5
sex             Male
smoker           Yes
day              Sun
time          Dinner
size               4
Name: 183, dtype: object

In [24]:
# rudest table, which table left the smallest tip relative to the bill each day

In [25]:
bookings = pd.read_csv("../Data/bookings.csv")

print(bookings)

    booking_id        customer  day    time  party_size
0          101     ravi sharma  Sat  Dinner         4.0
1          102      PRIYA IYER  Sat  Dinner         2.0
2          103    Ravi Sharma   Sun   Lunch         NaN
3          104      amit kumar  Sun  Dinner         6.0
4          105     priya  iyer  Fri  Dinner         NaN
5          106     RAVI SHARMA  Sat   Lunch         3.0
6          107       sana khan  Sat   Lunch         NaN
7          108      Amit Kumar  Sat  Dinner         5.0
8          109      vikram rao  Sun  Dinner         2.0
9          110      Sana  Khan  Fri  Dinner         4.0
10         111      priya iyer  Sat   Lunch         NaN
11         112      VIKRAM RAO  Sun   Lunch         3.0

In [47]:
# print("customer name \n", bookings['customer'].str.lower().str.strip())


print( "customer \n", bookings['customer'].str.lower()\
                        .str.strip().str.split().str.join("")
)

customer
 0     ravisharma
1      priyaiyer
2     ravisharma
3      amitkumar
4      priyaiyer
5     ravisharma
6       sanakhan
7      amitkumar
8      vikramrao
9       sanakhan
10     priyaiyer
11     vikramrao
Name: customer, dtype: object

In [48]:
bookings['customer'] = (bookings['customer']
                        .str.lower()
                        .str.strip()
                        .str.split()
                        .str.join(""))

print(bookings['customer'].nunique())

5